### ISSUE TITLE
[Card] [Instant messaging] There is no icon for QQ in card

### ISSUE THREAD

**Issue by xMudrii** [ruzpuz/advanced-vcard#10]
### Tested on:
**Browser:** Google Chrome v52.0.2743.82 (64-bit)
**OS:** Ubuntu Desktop 16.04

### How to reproduce bug:
* Login
* Go to Administration/Basic Informations
* Add QQ instant messaging
* Open your card and go to instant messaging tab.

QQ account is shown without icon for it.

##### Is there even icon for QQ ?

**Comment by xMudrii** [comment]
## Possible bugfix:

In CSS file there is already defined icon for QQ but wrong class is being called in card.
Card calls .vc-instant-messaging-QQ instead of .vc-instant-messaging-qq.

This can fixed by changing class name from 
.vc-instant-messaging-qq:before TO -> .vc-instant-messaging-QQ:before
or by changing what card calls.

This in business-card.css at line 70.

**Comment by ruzpuz** [comment]
done.
