### ISSUE TITLE
[Image Crop] You are allowed to crop outside of narrow but tall image

### ISSUE THREAD

**Issue by xMudrii** [ruzpuz/advanced-vcard#11]
### Tested on:
**Browser:** Google Chrome v52.0.2743.82 (64-bit)
**OS:** Ubuntu Desktop 16.04

### How to reproduce bug:
* Login
* Go to Administration/Basic Informations
* Add narrow/tall image
* Try to resize image crop circle outside of image.
* Crop
* Open your card and go to Informations tab.

**Expected results:**
You are not allowed to crop (or resize crop circle) outside of image.

**Observed results:**
You are allowed to crop outside of image. This makes your image in card to have white space.
*Note: It can be extended outside of image only for a few pixels but it still shows white space on image.*

**Comment by ruzpuz** [comment]
I'm afraid that is 3rd party software issue.
