### ISSUE TITLE
[Admin panel] [Basic Informations-UI] Copy button have low width

### ISSUE THREAD

**Issue by xMudrii** [ruzpuz/advanced-vcard#16]
### Tested on:
**Browser:** Firefox 47.0/Google Chrome v52.0.2743.82 (64-bit)
**OS:** Ubuntu Desktop 16.04

### How to reproduce bug:
* Login
* Go to Administration / Basic Informations
* Click on Copy button anywhere in button div

**Expected results:**
It copies the link.

**Observed results:**
You must click on "Copy" text to copy link. Button div is wider but button size is size of Copy text.

**Bugfix:**
Adding width: 100% on button fix the problem.
It can be added to button class - vc-button-copy in forms.css file (line 45).

**Comment by ruzpuz** [comment]
accepted. to be tested
