### ISSUE TITLE
[Log In] [UI] Logging in message is right aligned

### ISSUE THREAD

**Issue by xMudrii** [ruzpuz/advanced-vcard#17]
#### Environment
OS : **Ubuntu Desktop 16.04.1 - x64**
Browser: **Firefox 47.0**
Browser: **Google Chrome v52.0.2743.82 (64-bit)**

#### Description
*'Logging in'* message is now aligned on right side of form.

#### How to reproduce steps
* Go to Log in form
* Enter credentials
* Click Log in and watch for *'Logging in'* message

#### Important notice:
~~This bug started as of 9e24fa14071773e0a2d8476d908b69f762d73213 commit!~~
**This bug started as of 3ebbb4a04bbd64611c55b272ab76d627cfe3839f commit!**
Root of problem is added *float:right;* in **error-messages** CSS class 
of **forms.css** (class is on line 24). Removing *float:right;* from **error-messages** class
return *'Logging in'* message in center of form.

#### Screenshot of bug
![Screenshot of bug](http://i.imgur.com/484qQGu.png)

**Comment by ruzpuz** [comment]
this was fixed but not pushed to test server.
