### ISSUE TITLE
[Card] [Mobile] Full name on card is not centered

### ISSUE THREAD

**Issue by xMudrii** [ruzpuz/advanced-vcard#18]
#### Environment
Device : **BlackBerry Z30**
OS : **Blackberry OS 10.3.2.2836**
Browser: **Browser**

#### Description
Full name on first page of card is aligned right

#### Screenshot of bug
![Screenshot of bug](http://i.imgur.com/CSaT7iI.png)

**Comment by xMudrii** [comment]
#### How to reproduce bug
* Open your card or someone others card

## Possible bugfix for this bug
As far as I had change to test there is one possible bugfix.
Adding -webkit-transform : translate(-50%, -50%); property in .vc-fullname class at
business-card.css at line 7 fixes the problem for Blackberry (webkit) based browsers

**Comment by ruzpuz** [comment]
@xMudrii  is it okay on BB devices now?

**Comment by xMudrii** [comment]
Yes it is, both in portrait and landscape modes :+1:
