### ISSUE TITLE
[Social Networks] [Twitter-UI] Connecting with non-existing Twitter account shows disconnect option and successful status (green dot)

### ISSUE THREAD

**Issue by xMudrii** [ruzpuz/advanced-vcard#2]
### Tested on:
**Browser:** Google Chrome v52.0.2743.82 (64-bit)
**OS:** Ubuntu Desktop 16.04

### How to reproduce bug:
* Login
* Go to Administration/Social Networks
* Try to connect with non-existing Twitter account (eg. qwerqwrqwrqw)
* Click OK on no-such user popup

**Expected results:**
Field for Twitter username is cleaned and Twitter account is disconnected.

**Observed results:**
Twitter account is connected with non-existing account. There is option disconnect and green dot showing successful connection.

**NOTE:** There is No such user popup message. 
**After refreshing page you are not anymore connected to non-existing account.**

**Comment by ruzpuz** [comment]
The issue is fixed
