### ISSUE TITLE
[Admin panel] [Wallet] Cards without profile image have weird gray border

### ISSUE THREAD

**Issue by xMudrii** [ruzpuz/advanced-vcard#21]
### Tested on:
**Browser:** Opera 39.0.2256.43 Stable
**OS:** Ubuntu Desktop 16.04.1 x64

### How to reproduce bug:
* Go to Log In page
* Go to your Wallet

**Expected results:**
Cards without profile image (with default profile image) shows normal as profiles with custom image.

**Observed results:**
Cards without profile image have weird gray border.

![Screenshot of bug](http://i.imgur.com/S3ewftD.png)

**Comment by ruzpuz** [comment]
@xMudrii please try this now.

**Comment by xMudrii** [comment]
@ruzpuz fixed.
