### ISSUE TITLE
[Social Networks] [LinkedIn] After removing BcHub app from LinkedIn Apps you can't connect anymore

### ISSUE THREAD

**Issue by xMudrii** [ruzpuz/advanced-vcard#4]
### Tested on:
**Browser:** Google Chrome v52.0.2743.82 (64-bit)
**OS:** Ubuntu Desktop 16.04

### How to reproduce bug:
* Login
* Go to Administration/Social Networks
* Connect to LinkedIn
* Click Disconnect
* Follow link
* Remove BcHub app
* Return to Admin panel/Social network
* Refresh page

**Expected results:**
Connect option is showed, you are able to reconnect again.

**Observed results:**
There is disconnect option with brown dot. You are not able to connect to LinkedIn account anymore.
Clicking on Disconnect opens popup with link to remove app from LinkedIn account settings.

**Comment by ruzpuz** [comment]
@xMudrii Fixed, closing.
