### ISSUE TITLE
[Social Networks] [LinkedIn-UI] There is no option to remove link to your LinkedIn profile in your card

### ISSUE THREAD

**Issue by xMudrii** [ruzpuz/advanced-vcard#5]
### Tested on:
**Browser:** Google Chrome v52.0.2743.82 (64-bit)
**OS:** Ubuntu Desktop 16.04

**Warning:** This bug is connected to bug #4 !

There is no any option to hide link to LinkedIn profile (or change it to another profile) in your Card.

Disconnect option/Removing app from LinkedIn Account Settings doesn't remove link from your card.

**Comment by ruzpuz** [comment]
Fix for https://github.com/ruzpuz/advanced-vcard/issues/4 will close it also. This is the consequence or mentioned issue so closing this.
