### ISSUE TITLE
[Card] [Informations] Address shows in two lines then animates in one line

### ISSUE THREAD

**Issue by xMudrii** [ruzpuz/advanced-vcard#9]
### Tested on:
**Browser:** Google Chrome v52.0.2743.82 (64-bit)
**OS:** Ubuntu Desktop 16.04

### How to reproduce bug:
* Login
* Go to Administration/Basic Informations
* Add your address
* Save
* Open your card and go to (Basic) Informations tab.

**Expected results:**
Your address shows from beginning in one line and correctly animates as Informations loads.

**Observed results:**
Your address shows in two lines and animates to show in one line as card loads.

**Comment by ruzpuz** [comment]
I will not consider this an issue for now.
